// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Accounts struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Contacts struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
	CompanyName sql.NullString `json:"company_name"`
	Address     sql.NullString `json:"address"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Goals struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	// e.g., "Increase meeting rates"
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	// standard or custom
	Type sql.NullString `json:"type"`
	// e.g., number of meetings to set
	TargetValue sql.NullString `json:"target_value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Users struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Email     string    `json:"email"`
	FullName  string    `json:"full_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
